using System.Collections.Concurrent;
using System.Net;
using System.Security.Cryptography;
using System.Text;
using Microsoft.AspNetCore.HttpOverrides;
using Microsoft.AspNetCore.RateLimiting;
using Microsoft.Extensions.Caching.Memory;
using System.Threading.RateLimiting;

var builder = WebApplication.CreateBuilder(args);
builder.Logging.AddFilter("System.Net.Http.HttpClient", LogLevel.Warning);
var settings = MarketplaceSettings.FromEnvironment();
builder.Services.AddSingleton(settings);builder.Services.AddSingleton<MarketplaceSessionStore>();builder.Services.AddMemoryCache();
builder.Services.AddHttpClient("terraria-wiki", client=>{client.BaseAddress=new Uri("https://terraria.wiki.gg/");client.Timeout=TimeSpan.FromSeconds(12);client.DefaultRequestHeaders.UserAgent.ParseAdd("ArkoviaMarketplace/1.0 (+https://arkovia-node1.mywire.org/marketplace)");});
builder.Services.AddHttpClient<TShockMarketplaceClient>((sp,client)=>{client.BaseAddress=new Uri(sp.GetRequiredService<MarketplaceSettings>().TShockBaseUrl);client.Timeout=TimeSpan.FromSeconds(15);});
builder.Services.Configure<ForwardedHeadersOptions>(o=>{o.ForwardedHeaders=ForwardedHeaders.XForwardedFor|ForwardedHeaders.XForwardedProto;o.KnownNetworks.Clear();o.KnownProxies.Clear();o.KnownProxies.Add(IPAddress.Loopback);o.KnownProxies.Add(IPAddress.IPv6Loopback);});
builder.Services.AddRateLimiter(o=>{o.RejectionStatusCode=429;o.GlobalLimiter=PartitionedRateLimiter.Create<HttpContext,string>(c=>RateLimitPartition.GetFixedWindowLimiter(c.Connection.RemoteIpAddress?.ToString()??"unknown",_=>new FixedWindowRateLimiterOptions{PermitLimit=120,Window=TimeSpan.FromMinutes(1),QueueLimit=0,AutoReplenishment=true}));o.AddFixedWindowLimiter("link",l=>{l.PermitLimit=8;l.Window=TimeSpan.FromMinutes(5);l.QueueLimit=0;l.AutoReplenishment=true;});o.AddFixedWindowLimiter("chat",l=>{l.PermitLimit=8;l.Window=TimeSpan.FromSeconds(20);l.QueueLimit=0;l.AutoReplenishment=true;});});
var app=builder.Build();app.UseForwardedHeaders();
app.Use(async(context,next)=>{context.Response.Headers["X-Content-Type-Options"]="nosniff";context.Response.Headers["X-Frame-Options"]="DENY";context.Response.Headers["Referrer-Policy"]="no-referrer";context.Response.Headers["Permissions-Policy"]="camera=(), microphone=(), geolocation=()";context.Response.Headers["Content-Security-Policy"]="default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data: https://terraria.wiki.gg https://cdn.discordapp.com; frame-src https://discord.com; connect-src 'self'; object-src 'none'; base-uri 'none'; frame-ancestors 'none'; form-action 'self'";if(context.Request.IsHttps)context.Response.Headers["Strict-Transport-Security"]="max-age=31536000; includeSubDomains";await next();});
app.UseRateLimiter();app.UseStaticFiles();
app.MapGet("/",()=>Results.Redirect("/marketplace"));app.MapGet("/marketplace",(IWebHostEnvironment env)=>Results.File(Path.Combine(env.WebRootPath,"index.html"),"text/html; charset=utf-8"));app.MapGet("/healthz",()=>Results.Ok(new{status="ok",service="arkovia-marketplace"}));
app.MapGet("/readyz",async(TShockMarketplaceClient tshock,CancellationToken ct)=>{var u=await tshock.GetAsync("/marketplace/api/v1/status",ct);return u.IsSuccess?Results.Ok(new{status="ready",upstream="tshock"}):Results.Json(new{status="degraded",upstream="tshock"},statusCode:503);});
app.MapGet("/api/status",async(TShockMarketplaceClient t,CancellationToken ct)=>await Proxy(await t.GetAsync("/marketplace/api/v1/status",ct)));
app.MapGet("/api/players",async(TShockMarketplaceClient t,CancellationToken ct)=>await Proxy(await t.GetAsync("/marketplace/api/v1/players",ct)));
app.MapGet("/api/chat",async(long? after,TShockMarketplaceClient t,CancellationToken ct)=>await Proxy(await t.GetAsync($"/marketplace/api/v1/chat/{Math.Max(0,after??0)}",ct)));
app.MapGet("/api/listings",async(TShockMarketplaceClient t,CancellationToken ct)=>await Proxy(await t.GetAsync("/marketplace/api/v1/listings?limit=100",ct)));
app.MapGet("/api/stocks",async(TShockMarketplaceClient t,CancellationToken ct)=>await Proxy(await t.GetAsync("/marketplace/api/v1/stocks",ct)));
app.MapGet("/api/stocks/{ticker}",async(string ticker,TShockMarketplaceClient t,CancellationToken ct)=>await Proxy(await t.GetAsync($"/marketplace/api/v1/stocks/{Uri.EscapeDataString(ticker)}",ct)));
app.MapGet("/api/inventory",async(HttpContext c,MarketplaceSessionStore s,TShockMarketplaceClient t,CancellationToken ct)=>!s.TryGet(c,out var x)?Results.Unauthorized():await Proxy(await t.GetAsync($"/marketplace/api/v1/player/inventory/{Uri.EscapeDataString(x.WebSubject)}",ct)));
app.MapGet("/api/pets/catalog",async(TShockMarketplaceClient t,CancellationToken ct)=>await Proxy(await t.GetAsync("/marketplace/api/v1/pets/catalog",ct)));
app.MapGet("/api/pets/me",async(HttpContext c,MarketplaceSessionStore s,TShockMarketplaceClient t,CancellationToken ct)=>!s.TryGet(c,out var x)?Results.Unauthorized():await Proxy(await t.GetAsync($"/marketplace/api/v1/pets/me/{Uri.EscapeDataString(x.WebSubject)}",ct)));
app.MapGet("/api/item-image/{itemId:int}",async(int itemId,string? name,IHttpClientFactory clients,IMemoryCache cache,CancellationToken ct)=>{if(itemId<=0||itemId>100000)return Results.NotFound();var clean=(name??"").Trim();if(clean.Length is <1 or >128||clean.Any(c=>char.IsControl(c)||c is '/' or '\\'))return Results.NotFound();var key=$"terraria-item-image:{itemId}:{clean}";if(cache.TryGetValue(key,out byte[]? cached)&&cached is{Length:>0})return Results.File(cached,"image/png");var client=clients.CreateClient("terraria-wiki");using var req=new HttpRequestMessage(HttpMethod.Get,"wiki/Special:Redirect/file/"+Uri.EscapeDataString(clean.Replace(' ','_')+".png"));req.Headers.Referrer=new Uri("https://terraria.wiki.gg/");using var resp=await client.SendAsync(req,HttpCompletionOption.ResponseHeadersRead,ct);if(!resp.IsSuccessStatusCode||resp.Content.Headers.ContentType?.MediaType!="image/png"||resp.Content.Headers.ContentLength is >1000000)return Results.NotFound();var bytes=await resp.Content.ReadAsByteArrayAsync(ct);if(bytes.Length is <1 or >1000000)return Results.NotFound();cache.Set(key,bytes,TimeSpan.FromDays(7));return Results.File(bytes,"image/png");});
app.MapGet("/api/pet-image/{itemId:int}",async(int itemId,string? petName,string? itemName,IHttpClientFactory clients,IMemoryCache cache,CancellationToken ct)=>{if(itemId<=0||itemId>100000)return Results.NotFound();var names=new[]{petName,itemName}.Where(x=>!string.IsNullOrWhiteSpace(x)).Select(x=>x!.Trim()).Where(x=>x.Length<=128&&!x.Any(c=>char.IsControl(c)||c is '/' or '\\')).Distinct(StringComparer.OrdinalIgnoreCase).ToArray();if(names.Length==0)return Results.NotFound();var client=clients.CreateClient("terraria-wiki");foreach(var n in names){var key=$"terraria-pet-image:{itemId}:{n}";if(cache.TryGetValue(key,out byte[]? cached)&&cached is{Length:>0})return Results.File(cached,"image/png");try{using var req=new HttpRequestMessage(HttpMethod.Get,"wiki/Special:Redirect/file/"+Uri.EscapeDataString(n.Replace(' ','_')+".png"));req.Headers.Referrer=new Uri("https://terraria.wiki.gg/");using var resp=await client.SendAsync(req,HttpCompletionOption.ResponseHeadersRead,ct);if(!resp.IsSuccessStatusCode||resp.Content.Headers.ContentType?.MediaType!="image/png"||resp.Content.Headers.ContentLength is >1000000)continue;var bytes=await resp.Content.ReadAsByteArrayAsync(ct);if(bytes.Length is <1 or >1000000)continue;cache.Set(key,bytes,TimeSpan.FromDays(7));return Results.File(bytes,"image/png");}catch{}}return Results.NotFound();});
app.MapGet("/api/session",(HttpContext c,MarketplaceSessionStore s)=>!s.TryGet(c,out var x)?Results.Ok(new{authenticated=false}):Results.Ok(new{authenticated=true,accountName=x.AccountName,csrfToken=x.CsrfToken,expiresUtc=x.ExpiresUtc}));
app.MapPost("/api/auth/link",async(LinkRequest request,HttpContext context,MarketplaceSettings cfg,MarketplaceSessionStore sessions,TShockMarketplaceClient tshock,CancellationToken ct)=>{var account=(request.Account??"").Trim();var code=(request.Code??"").Trim();if(account.Length is <1 or >64||code.Length!=6||!code.All(char.IsDigit))return Results.BadRequest(new{error="Enter your ARK wallet address and the 6-digit authentication code from /market auth."});var requested=cfg.SubjectForAccount(account);var linked=await tshock.GetAsync($"/marketplace/api/v1/link/{Uri.EscapeDataString(account)}/{Uri.EscapeDataString(code)}/{Uri.EscapeDataString(requested)}",ct);if(!linked.IsSuccess)return await Proxy(linked);var subject=requested;var accountName=account;try{using var doc=System.Text.Json.JsonDocument.Parse(linked.Body);var root=doc.RootElement;if(root.TryGetProperty("webSubject",out var ws)&&!string.IsNullOrWhiteSpace(ws.GetString()))subject=ws.GetString()!;if(root.TryGetProperty("accountName",out var an)&&!string.IsNullOrWhiteSpace(an.GetString()))accountName=an.GetString()!;}catch{}var session=sessions.Create(subject,accountName,request.RememberMe);context.Response.Cookies.Append(MarketplaceSessionStore.CookieName,session.SessionId,new CookieOptions{HttpOnly=true,Secure=cfg.CookieSecure,SameSite=SameSiteMode.Strict,Path="/",MaxAge=session.ExpiresUtc-DateTime.UtcNow,IsEssential=true});return Results.Ok(new{authenticated=true,accountName=session.AccountName,csrfToken=session.CsrfToken,expiresUtc=session.ExpiresUtc,remembered=request.RememberMe});}).RequireRateLimiting("link");
app.MapPost("/api/chat",async(RealmChatRequest r,HttpContext c,MarketplaceSessionStore sessions,TShockMarketplaceClient t,CancellationToken ct)=>{if(!sessions.TryGet(c,out var x))return Results.Unauthorized();if(!RequireCsrf(c,x))return Results.StatusCode(403);var message=(r.Message??"").Trim();if(message.Length is <1 or >240||message.Any(char.IsControl))return Results.BadRequest(new{error="Message must be 1-240 characters."});return await Proxy(await t.GetAsync($"/marketplace/api/v1/chat/send/{Uri.EscapeDataString(x.WebSubject)}/{Uri.EscapeDataString(message)}",ct));}).RequireRateLimiting("chat");
app.MapPost("/api/pets/adopt",async(PetActionRequest r,HttpContext c,MarketplaceSessionStore sessions,TShockMarketplaceClient t,CancellationToken ct)=>{if(!sessions.TryGet(c,out var x))return Results.Unauthorized();if(!RequireCsrf(c,x))return Results.StatusCode(403);if(!TryOperationKey(c,out var op,out var err))return err!;if(r.ItemId<=0)return Results.BadRequest(new{error="Invalid pet item ID."});return await Proxy(await t.GetAsync($"/marketplace/api/v1/mutate/pet-adopt/{Uri.EscapeDataString(x.WebSubject)}/{r.ItemId}/{Uri.EscapeDataString(op)}",ct));});
app.MapPost("/api/pets/care",async(PetCareRequest r,HttpContext c,MarketplaceSessionStore sessions,TShockMarketplaceClient t,CancellationToken ct)=>{if(!sessions.TryGet(c,out var x))return Results.Unauthorized();if(!RequireCsrf(c,x))return Results.StatusCode(403);if(!TryOperationKey(c,out var op,out var err))return err!;var action=(r.Action??"").Trim().ToLowerInvariant();if(r.ItemId<=0||action is not ("feed" or "play" or "groom" or "rest"))return Results.BadRequest(new{error="Invalid pet care action."});return await Proxy(await t.GetAsync($"/marketplace/api/v1/mutate/pet-care/{Uri.EscapeDataString(x.WebSubject)}/{r.ItemId}/{Uri.EscapeDataString(action)}/{Uri.EscapeDataString(op)}",ct));});
app.MapPost("/api/pets/active",async(PetActionRequest r,HttpContext c,MarketplaceSessionStore sessions,TShockMarketplaceClient t,CancellationToken ct)=>{if(!sessions.TryGet(c,out var x))return Results.Unauthorized();if(!RequireCsrf(c,x))return Results.StatusCode(403);if(!TryOperationKey(c,out var op,out var err))return err!;if(r.ItemId<=0)return Results.BadRequest(new{error="Invalid pet item ID."});return await Proxy(await t.GetAsync($"/marketplace/api/v1/mutate/pet-active/{Uri.EscapeDataString(x.WebSubject)}/{r.ItemId}/{Uri.EscapeDataString(op)}",ct));});
app.MapPost("/api/pets/rename",async(PetRenameRequest r,HttpContext c,MarketplaceSessionStore sessions,TShockMarketplaceClient t,CancellationToken ct)=>{if(!sessions.TryGet(c,out var x))return Results.Unauthorized();if(!RequireCsrf(c,x))return Results.StatusCode(403);if(!TryOperationKey(c,out var op,out var err))return err!;var name=(r.Name??"").Trim();if(r.ItemId<=0||name.Length is <2 or >24||name.Any(char.IsControl))return Results.BadRequest(new{error="Companion names must be 2-24 readable characters."});return await Proxy(await t.GetAsync($"/marketplace/api/v1/mutate/pet-rename/{Uri.EscapeDataString(x.WebSubject)}/{r.ItemId}/{Uri.EscapeDataString(name)}/{Uri.EscapeDataString(op)}",ct));});
app.MapPost("/api/pets/adventure",async(PetActionRequest r,HttpContext c,MarketplaceSessionStore sessions,TShockMarketplaceClient t,CancellationToken ct)=>{if(!sessions.TryGet(c,out var x))return Results.Unauthorized();if(!RequireCsrf(c,x))return Results.StatusCode(403);if(!TryOperationKey(c,out var op,out var err))return err!;if(r.ItemId<=0)return Results.BadRequest(new{error="Invalid pet item ID."});return await Proxy(await t.GetAsync($"/marketplace/api/v1/mutate/pet-adventure/{Uri.EscapeDataString(x.WebSubject)}/{r.ItemId}/{Uri.EscapeDataString(op)}",ct));});
app.MapGet("/api/pets/journal",async(HttpContext c,MarketplaceSessionStore sessions,TShockMarketplaceClient t,CancellationToken ct)=>!sessions.TryGet(c,out var x)?Results.Unauthorized():await Proxy(await t.GetAsync($"/marketplace/api/v1/pets/journal/{Uri.EscapeDataString(x.WebSubject)}",ct)));
app.MapPost("/api/auth/logout",(HttpContext c,MarketplaceSettings cfg,MarketplaceSessionStore s)=>{if(!s.TryGet(c,out var x))return Results.Ok(new{authenticated=false});if(!RequireCsrf(c,x))return Results.StatusCode(403);s.Remove(x.SessionId);c.Response.Cookies.Delete(MarketplaceSessionStore.CookieName,new CookieOptions{HttpOnly=true,Secure=cfg.CookieSecure,SameSite=SameSiteMode.Strict,Path="/"});return Results.Ok(new{authenticated=false});});
app.MapGet("/api/me",async(HttpContext c,MarketplaceSessionStore s,TShockMarketplaceClient t,CancellationToken ct)=>!s.TryGet(c,out var x)?Results.Unauthorized():await Proxy(await t.GetAsync($"/marketplace/api/v1/me/{Uri.EscapeDataString(x.WebSubject)}",ct)));
app.MapPost("/api/marketplace/inventory-list",async(InventoryListingRequest r,HttpContext c,MarketplaceSessionStore s,TShockMarketplaceClient t,CancellationToken ct)=>{if(!s.TryGet(c,out var x))return Results.Unauthorized();if(!RequireCsrf(c,x))return Results.StatusCode(403);if(!TryOperationKey(c,out var op,out var err))return err!;if(r.Slot<0||r.Slot>58||r.Quantity<=0||!long.TryParse(r.PriceAtomic,out var price)||price<=0)return Results.BadRequest(new{error="Invalid inventory listing values."});return await Proxy(await t.GetAsync($"/marketplace/api/v1/mutate/inventory-list/{Uri.EscapeDataString(x.WebSubject)}/{r.Slot}/{r.Quantity}/{price}/{Uri.EscapeDataString(op)}",ct));});
app.MapPost("/api/stocks/buy",async(StockBuyRequest r,HttpContext c,MarketplaceSessionStore s,TShockMarketplaceClient t,CancellationToken ct)=>{if(!s.TryGet(c,out var x))return Results.Unauthorized();if(!RequireCsrf(c,x))return Results.StatusCode(403);if(!TryOperationKey(c,out var op,out var err))return err!;var ticker=(r.Ticker??"").Trim().ToUpperInvariant();if(r.Shares<=0||r.Shares>1000000||ticker.Length<1||ticker.Length>12)return Results.BadRequest(new{error="Invalid stock purchase."});return await Proxy(await t.GetAsync($"/marketplace/api/v1/mutate/stock-buy/{Uri.EscapeDataString(x.WebSubject)}/{Uri.EscapeDataString(ticker)}/{r.Shares}/{Uri.EscapeDataString(op)}",ct));});
app.MapPost("/api/marketplace/claim-items",async(HttpContext c,MarketplaceSessionStore s,TShockMarketplaceClient t,CancellationToken ct)=>{if(!s.TryGet(c,out var x))return Results.Unauthorized();if(!RequireCsrf(c,x))return Results.StatusCode(403);if(!TryOperationKey(c,out var op,out var err))return err!;return await Proxy(await t.GetAsync($"/marketplace/api/v1/mutate/claim-items/{Uri.EscapeDataString(x.WebSubject)}/{Uri.EscapeDataString(op)}",ct));});
app.MapPost("/api/marketplace/list",async(ListingRequest r,HttpContext c,MarketplaceSessionStore s,TShockMarketplaceClient t,CancellationToken ct)=>{if(!s.TryGet(c,out var x))return Results.Unauthorized();if(!RequireCsrf(c,x))return Results.StatusCode(403);if(!TryOperationKey(c,out var op,out var err))return err!;var id=(r.AssetId??"").Trim();if(!id.StartsWith("ARK-ASSET-",StringComparison.Ordinal)||id.Length>64||!long.TryParse((r.PriceAtomic??"").Trim(),out var price)||price<=0)return Results.BadRequest(new{error="Invalid listing."});return await Proxy(await t.GetAsync($"/marketplace/api/v1/mutate/list/{Uri.EscapeDataString(x.WebSubject)}/{Uri.EscapeDataString(id)}/{price}/{Uri.EscapeDataString(op)}",ct));});
app.MapPost("/api/marketplace/buy",async(ListingActionRequest r,HttpContext c,MarketplaceSessionStore s,TShockMarketplaceClient t,CancellationToken ct)=>{if(!s.TryGet(c,out var x))return Results.Unauthorized();if(!RequireCsrf(c,x))return Results.StatusCode(403);if(!TryOperationKey(c,out var op,out var err))return err!;if(!TryListingId(r.ListingId,out var id))return Results.BadRequest(new{error="Invalid listing ID."});return await Proxy(await t.GetAsync($"/marketplace/api/v1/mutate/buy/{Uri.EscapeDataString(x.WebSubject)}/{Uri.EscapeDataString(id)}/{Uri.EscapeDataString(op)}",ct));});
app.MapPost("/api/marketplace/cancel",async(ListingActionRequest r,HttpContext c,MarketplaceSessionStore s,TShockMarketplaceClient t,CancellationToken ct)=>{if(!s.TryGet(c,out var x))return Results.Unauthorized();if(!RequireCsrf(c,x))return Results.StatusCode(403);if(!TryOperationKey(c,out var op,out var err))return err!;if(!TryListingId(r.ListingId,out var id))return Results.BadRequest(new{error="Invalid listing ID."});return await Proxy(await t.GetAsync($"/marketplace/api/v1/mutate/cancel/{Uri.EscapeDataString(x.WebSubject)}/{Uri.EscapeDataString(id)}/{Uri.EscapeDataString(op)}",ct));});
app.Run();
static bool TryListingId(string? v,out string id){id=(v??"").Trim();return id.StartsWith("ARK-LIST-",StringComparison.Ordinal)&&id.Length is >=10 and <=64;}
static bool TryOperationKey(HttpContext c,out string op,out IResult? error){op=c.Request.Headers["Idempotency-Key"].ToString().Trim();if(op.Length is <12 or >96||!op.All(ch=>char.IsLetterOrDigit(ch)||ch is '-' or '_' or '.' or ':')){error=Results.BadRequest(new{error="A valid Idempotency-Key header is required."});return false;}error=null;return true;}
static bool RequireCsrf(HttpContext c,MarketplaceSession s){var p=c.Request.Headers["X-CSRF-Token"].ToString();return p.Length==s.CsrfToken.Length&&CryptographicOperations.FixedTimeEquals(Encoding.UTF8.GetBytes(p),Encoding.UTF8.GetBytes(s.CsrfToken));}
static async Task<IResult> Proxy(ProxyResponse r){await Task.CompletedTask;return Results.Content(r.Body,"application/json; charset=utf-8",Encoding.UTF8,(int)r.StatusCode);}
sealed record LinkRequest(string? Account,string? Code,bool RememberMe=false);sealed record RealmChatRequest(string? Message);sealed record PetActionRequest(int ItemId);sealed record PetCareRequest(int ItemId,string? Action);sealed record PetRenameRequest(int ItemId,string? Name);sealed record ListingRequest(string? AssetId,string? PriceAtomic);sealed record InventoryListingRequest(int Slot,int Quantity,string? PriceAtomic);sealed record StockBuyRequest(string? Ticker,long Shares);sealed record ListingActionRequest(string? ListingId);sealed record ProxyResponse(HttpStatusCode StatusCode,string Body){public bool IsSuccess=>(int)StatusCode is >=200 and <=299;}
sealed class MarketplaceSettings{public required string TShockBaseUrl{get;init;}public required string TShockToken{get;init;}public required string SubjectSecret{get;init;}public bool CookieSecure{get;init;}public TimeSpan SessionLifetime{get;init;}=TimeSpan.FromHours(12);public TimeSpan RememberedSessionLifetime{get;init;}=TimeSpan.FromDays(30);public string SubjectForAccount(string a){using var h=new HMACSHA256(Encoding.UTF8.GetBytes(SubjectSecret));return "web:"+Convert.ToHexString(h.ComputeHash(Encoding.UTF8.GetBytes(a.Trim().ToLowerInvariant()))).ToLowerInvariant();}public static MarketplaceSettings FromEnvironment(){static string R(string n){var v=Environment.GetEnvironmentVariable(n)?.Trim();if(string.IsNullOrWhiteSpace(v))throw new InvalidOperationException($"Required environment variable {n} is not configured.");return v;}var u=Environment.GetEnvironmentVariable("ARKOVIA_TSHOCK_REST_URL")?.Trim();if(string.IsNullOrWhiteSpace(u))u="http://127.0.0.1:7878";if(!u.EndsWith('/'))u+="/";var secret=R("ARKOVIA_MARKET_SUBJECT_SECRET");if(secret.Length<32)throw new InvalidOperationException("ARKOVIA_MARKET_SUBJECT_SECRET must be at least 32 characters.");return new MarketplaceSettings{TShockBaseUrl=u,TShockToken=R("ARKOVIA_TSHOCK_REST_TOKEN"),SubjectSecret=secret,CookieSecure=!string.Equals(Environment.GetEnvironmentVariable("ARKOVIA_MARKET_COOKIE_SECURE")?.Trim(),"false",StringComparison.OrdinalIgnoreCase)};}}
sealed record MarketplaceSession(string SessionId,string WebSubject,string AccountName,string CsrfToken,DateTime ExpiresUtc);
sealed record MarketplaceSessionPayload(int Version,string WebSubject,string AccountName,string CsrfToken,long ExpiresUnix);
sealed class MarketplaceSessionStore
{
    public const string CookieName="arkovia_market_session";
    private readonly MarketplaceSettings _settings;
    private readonly byte[] _signingKey;
    public MarketplaceSessionStore(MarketplaceSettings s)
    {
        _settings=s;
        using var h=new HMACSHA256(Encoding.UTF8.GetBytes(s.SubjectSecret));
        _signingKey=h.ComputeHash(Encoding.UTF8.GetBytes("arkovia-market-session-v1"));
    }
    public MarketplaceSession Create(string subject,string account,bool rememberMe=false)
    {
        var expires=DateTime.UtcNow.Add(rememberMe?_settings.RememberedSessionLifetime:_settings.SessionLifetime);
        var csrf=Convert.ToHexString(RandomNumberGenerator.GetBytes(32)).ToLowerInvariant();
        var payload=new MarketplaceSessionPayload(1,subject,account,csrf,new DateTimeOffset(expires).ToUnixTimeSeconds());
        var token=Protect(payload);
        return new MarketplaceSession(token,subject,account,csrf,expires);
    }
    public bool TryGet(HttpContext c,out MarketplaceSession s)
    {
        s=null!;
        if(!c.Request.Cookies.TryGetValue(CookieName,out var token)||string.IsNullOrWhiteSpace(token))return false;
        MarketplaceSessionPayload? p;
        try{p=Unprotect(token);}catch{return false;}
        if(p is null||p.Version!=1||string.IsNullOrWhiteSpace(p.WebSubject)||string.IsNullOrWhiteSpace(p.AccountName)||string.IsNullOrWhiteSpace(p.CsrfToken))return false;
        var expires=DateTimeOffset.FromUnixTimeSeconds(p.ExpiresUnix).UtcDateTime;
        if(expires<=DateTime.UtcNow)return false;
        s=new MarketplaceSession(token,p.WebSubject,p.AccountName,p.CsrfToken,expires);
        return true;
    }
    public void Remove(string id){ }
    private string Protect(MarketplaceSessionPayload payload)
    {
        var body=System.Text.Json.JsonSerializer.SerializeToUtf8Bytes(payload);
        using var h=new HMACSHA256(_signingKey);
        var sig=h.ComputeHash(body);
        return Microsoft.AspNetCore.WebUtilities.WebEncoders.Base64UrlEncode(body)+"."+Microsoft.AspNetCore.WebUtilities.WebEncoders.Base64UrlEncode(sig);
    }
    private MarketplaceSessionPayload? Unprotect(string token)
    {
        var parts=token.Split('.',2);if(parts.Length!=2)return null;
        var body=Microsoft.AspNetCore.WebUtilities.WebEncoders.Base64UrlDecode(parts[0]);
        var supplied=Microsoft.AspNetCore.WebUtilities.WebEncoders.Base64UrlDecode(parts[1]);
        using var h=new HMACSHA256(_signingKey);var expected=h.ComputeHash(body);
        if(supplied.Length!=expected.Length||!CryptographicOperations.FixedTimeEquals(supplied,expected))return null;
        return System.Text.Json.JsonSerializer.Deserialize<MarketplaceSessionPayload>(body);
    }
}
sealed class TShockMarketplaceClient{private readonly HttpClient _http;private readonly MarketplaceSettings _settings;public TShockMarketplaceClient(HttpClient h,MarketplaceSettings s){_http=h;_settings=s;}public async Task<ProxyResponse> GetAsync(string path,CancellationToken ct){var sep=path.Contains('?')?'&':'?';using var req=new HttpRequestMessage(HttpMethod.Get,path+sep+"token="+Uri.EscapeDataString(_settings.TShockToken));req.Headers.TryAddWithoutValidation("Accept","application/json");using var resp=await _http.SendAsync(req,HttpCompletionOption.ResponseHeadersRead,ct);var body=await resp.Content.ReadAsStringAsync(ct);if(body.Length>1000000)return new ProxyResponse(HttpStatusCode.BadGateway,"{\"error\":\"Upstream response was too large.\"}");return new ProxyResponse(resp.StatusCode,body);}}
